kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: skanmothelse
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SKANMOTHELSE_DOKARKIVJOURNALPOSTURL
      value: {{ SKANMOTHELSE_DOKARKIVJOURNALPOSTURL }}
    - name: SKANMOTHELSE_STSURL
      value: {{ SKANMOTHELSE_STSURL }}
    - name: SKANMOTHELSE_HELSE_SCHEDULE
      value: {{ SKANMOTHELSE_HELSE_SCHEDULE }}
    - name: SKANMOTHELSE_HELSE_SCHEDULE
      value: {{ SKANMOTHELSE_HELSE_SCHEDULE }}
    - name: SKANMOTHELSE_SFTP_PRIVATEKEY
      value: /var/run/secrets/nais.io/keys/privatekey
    - name: SKANMOTHELSE_SFTP_HOSTKEY
      value: /var/run/secrets/nais.io/keys/hostkey
    - name: SKANMOTHELSE_VAULT_BACKEND
      value: {{ SKANMOTHELSE_VAULT_BACKEND }}
    - name: SKANMOTHELSE_VAULT_KUBERNETESPATH
      value: {{ SKANMOTHELSE_VAULT_KUBERNETESPATH }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3584Mi
    requests:
      memory: 2560Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVSKANMOTHELSE }}
        mountPath: /var/run/secrets/nais.io/srvskanmothelse
      - kvPath: {{ SFTP_KEYS }}
        mountPath: /var/run/secrets/nais.io/keys
