kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: skanmothelse
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SKANMOTHELSE_ENDPOINTS_DOKARKIV_URL
      value: {{ SKANMOTHELSE_ENDPOINTS_DOKARKIV_URL }}
    - name: SKANMOTHELSE_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ SKANMOTHELSE_ENDPOINTS_DOKARKIV_SCOPE }}
    - name: SKANMOTHELSE_HELSE_SCHEDULE
      value: {{ SKANMOTHELSE_HELSE_SCHEDULE }}
    - name: SKANMOTHELSE_HELSE_SCHEDULE
      value: {{ SKANMOTHELSE_HELSE_SCHEDULE }}
    - name: SKANMOTHELSE_SFTP_PRIVATEKEY
      value: /var/run/secrets/nais.io/keys/privatekey
    - name: SKANMOTHELSE_SFTP_HOSTKEY
      value: /var/run/secrets/nais.io/keys/hostkey
    - name: SKANMOTHELSE_PGP_PRIVATEKEY
      value: /var/run/secrets/nais.io/keys/pgpprivatekey
    - name: SKANMOTHELSE_VAULT_BACKEND
      value: {{ SKANMOTHELSE_VAULT_BACKEND }}
    - name: SKANMOTHELSE_VAULT_KUBERNETESPATH
      value: {{ SKANMOTHELSE_VAULT_KUBERNETESPATH }}
    - name: SKANMOTHELSE_JIRA_URL
      value: {{ SKANMOTHELSE_JIRA_URL }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3584Mi
    requests:
      memory: 2560Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVSKANMOTHELSE }}
        mountPath: /var/run/secrets/nais.io/srvskanmothelse
      - kvPath: {{ SFTP_KEYS }}
        mountPath: /var/run/secrets/nais.io/keys
      - kvPath: {{ SRVJIRADOKDISTAVSTEMMING }}
        mountPath: /var/run/secrets/nais.io/srvjiradokdistavstemming
  azure:
    application:
      enabled: true
  webproxy: true